#!/usr/bin/env python3
"""
AutoWrec startup screen — Reverse Game of Life coalesce effect.

Loads precomputed GoL frames from a JSON file (generated by precompute_gol.py)
and plays them in reverse: scattered cells converge into "AutoWrec" text.
The right panel shows version/model info.

Runtime usage:
    from .autowrec_banner import show_startup
    show_startup(version="0.1.0", model="MCP")

Set AUTOWREC_NO_BANNER=1 to skip (CI, piped output).
"""

import json
import os
import shutil
import sys
import time
from pathlib import Path

from rich.console import Console
from rich.live import Live
from rich.table import Table
from rich.text import Text

_DATA_DIR = Path(__file__).parent / "data"

# Width thresholds
_COLS_FULL = 95  # full "AutoWrec" animation
_COLS_AQ = 50  # compact "AQ" animation
_COLS_Q = 20  # minimal "Q" animation
# below _COLS_Q → one-liner fallback


def _should_skip() -> bool:
    for var in ("AUTOWREC_NO_BANNER", "AUTOMATIQ_NO_BANNER"):
        if os.environ.get(var, "").strip() in ("1", "true", "yes"):
            return True
    if not sys.stdout.isatty():
        return True
    cols, _ = shutil.get_terminal_size((80, 24))
    if cols < _COLS_Q:
        return True
    return False


def _pick_frames_path() -> Path:
    """Return the appropriate frames file based on terminal width."""
    cols, _ = shutil.get_terminal_size((80, 24))
    if cols >= _COLS_FULL:
        return _DATA_DIR / "gol_frames.json"
    if cols >= _COLS_AQ:
        return _DATA_DIR / "gol_frames_aq.json"
    return _DATA_DIR / "gol_frames_q.json"


RESET = "\033[0m"
UPPER_HALF = "▀"
LOWER_HALF = "▄"


def _fg(r: int, g: int, b: int) -> str:
    return f"\033[38;2;{r};{g};{b}m"


def _bg(r: int, g: int, b: int) -> str:
    return f"\033[48;2;{r};{g};{b}m"


_PALETTE = [
    (0x00, 0xFF, 0xC8),  # #00FFC8  neon mint-green
    (0x00, 0xC8, 0xFF),  # #00C8FF  electric cyan
    (0xBF, 0x00, 0xFF),  # #BF00FF  neon violet
    (0xFF, 0x00, 0x9E),  # #FF009E  hot pink
]


def _hue_rgb(h: float) -> tuple[int, int, int]:
    """Interpolate a 0‥1 hue across the brand palette."""
    h = max(0.0, min(1.0, h))
    scaled = h * (len(_PALETTE) - 1)
    lo = int(scaled)
    hi = min(lo + 1, len(_PALETTE) - 1)
    t = scaled - lo
    r = int(_PALETTE[lo][0] + t * (_PALETTE[hi][0] - _PALETTE[lo][0]))
    g = int(_PALETTE[lo][1] + t * (_PALETTE[hi][1] - _PALETTE[lo][1]))
    b = int(_PALETTE[lo][2] + t * (_PALETTE[hi][2] - _PALETTE[lo][2]))
    return (r, g, b)


def _darken(rgb: tuple[int, int, int], factor: float = 0.25) -> tuple[int, int, int]:
    return tuple(int(c * factor) for c in rgb)


def _shine_blend(rgb: tuple[int, int, int], t: float) -> tuple[int, int, int]:
    """Blend rgb toward white by factor t (0=original, 1=pure white)."""
    return tuple(int(rgb[i] + (255 - rgb[i]) * t) for i in range(3))


def _load_frames(json_path: Path) -> tuple[list, int, int]:
    with open(json_path) as f:
        data = json.load(f)
    gh, gw = data["grid_h"], data["grid_w"]
    grids = []
    for frame_cells in data["frames"]:
        grid = [[None] * gw for _ in range(gh)]
        for r, c, hue in frame_cells:
            grid[r][c] = hue
        grids.append(grid)
    return grids, gh, gw


def _render_cell_region(grid: list, h: int, w: int, shine_pos: float = -999) -> str:
    """Render the GoL grid into a single ANSI string using half-block chars.

    shine_pos: centre of the shine band expressed as a diagonal index.
               Grid row 0 is stored at the visual bottom, so the screen
               diagonal is (h-1-r)+c — value 0 is top-left, sweeping
               low→high moves the band top-left → bottom-right.
    """
    BAND_HALF = 3

    lines = []
    for pr in range(0, h, 2):
        line = ""
        for c in range(w):
            top_r, bot_r = pr, pr + 1
            top_v = grid[top_r][c] if top_r < h else None
            bot_v = grid[bot_r][c] if bot_r < h else None

            # Shadow: pick up the hue of the cell diagonally above-left
            def _sh(r, c):
                sr, sc = r - 1, c - 1
                if 0 <= sr < h and 0 <= sc < w and grid[sr][sc] is not None:
                    return grid[sr][sc]
                return None

            if top_v is None:
                top_v = _sh(top_r, c)
                top_bright = False
            else:
                top_bright = True
            if bot_v is None:
                bot_v = _sh(bot_r, c)
                bot_bright = False
            else:
                bot_bright = True

            def _shine_t(r, _c=c):
                dist = abs(((h - 1 - r) + _c) - shine_pos)
                if dist >= BAND_HALF:
                    return 0.0
                return (1.0 - dist / BAND_HALF) * 0.85

            def _col(hue, bright, r):
                base = _hue_rgb(hue) if bright else _darken(_hue_rgb(hue))
                t = _shine_t(r)
                return _shine_blend(base, t) if t > 0 else base

            if top_v is None and bot_v is None:
                line += " "
            elif top_v is not None and bot_v is not None:
                tc = _col(top_v, top_bright, top_r)
                bc = _col(bot_v, bot_bright, bot_r)
                line += _fg(*tc) + _bg(*bc) + UPPER_HALF + RESET
            elif top_v is not None:
                tc = _col(top_v, top_bright, top_r)
                line += _fg(*tc) + UPPER_HALF + RESET
            else:
                bc = _col(bot_v, bot_bright, bot_r)
                line += _fg(*bc) + LOWER_HALF + RESET

        lines.append(line)

    return "\n".join(lines)


def _gradient_slogan() -> Text:
    t = Text()
    t.append("Your ", style="italic dim")
    t.append("activity", style="italic bold rgb(0,255,200)")
    t.append(", into ", style="italic dim")
    t.append("automation", style="italic bold rgb(255,0,158)")
    t.append(".", style="italic dim")
    return t


def _build_right_panel(version: str, model: str, recorder_model: str) -> Text:
    t = Text()
    t.append_text(_gradient_slogan())
    t.append("\n\n")
    t.append("Version ", style="dim")
    t.append(" ")
    t.append(f"v{version}", style="bold cyan")
    t.append("\n")
    t.append("Agent   ", style="dim")
    t.append(" ")
    t.append(model, style="white")
    t.append("\n")
    t.append("Recorder", style="dim")
    t.append(" ")
    t.append(recorder_model, style="white")
    return t


def _build_frame(cell_ansi: str, version: str, model: str, recorder_model: str) -> Table:
    table = Table.grid(padding=(0, 1))
    table.add_column(no_wrap=True)
    table.add_column(no_wrap=True)
    table.add_row(Text.from_ansi(cell_ansi), _build_right_panel(version, model, recorder_model))
    return table


def show_startup(
    version: str = "0.1.0",
    model: str = "gemini-2.5-flash",
    recorder_model: str = "",
    speed: float = 1.0,
    frames_path: Path | None = None,
) -> None:
    """Play the AutoWrec startup animation.

    Args:
        version:        Version string shown in the right panel.
        model:          Agent model name shown in the right panel.
        recorder_model: Recorder model name shown in the right panel.
        speed:          Multiplier — 1.0 = default, 2.0 = 2x faster, 0.5 = half speed.
        frames_path:    Path to gol_frames.json. Auto-detected if None.
    """
    if _should_skip():
        print(f"  \033[36m▸\033[0m \033[1mautowrec\033[0m \033[2mv{version} · {model}\033[0m")
        return

    if frames_path is None:
        frames_path = _pick_frames_path()

    try:
        forward_frames, gh, gw = _load_frames(frames_path)
    except (FileNotFoundError, KeyError, ValueError):
        print(f"  \033[36m▸\033[0m \033[1mautowrec\033[0m \033[2mv{version} · {model}\033[0m")
        return

    # Play in reverse: dissolved → coalesced
    frames = list(reversed(forward_frames))
    speed = max(speed, 0.01)

    # Shine band sweeps from off-screen top-left to off-screen bottom-right.
    # Pad by gw on each side so the band fully enters and exits the grid.
    SHINE_START = float(-gw)
    SHINE_END = float(gh + gw)
    SHINE_STEPS = 50
    SHINE_DELAY = 0.0325

    final_frame = frames[-1]
    console = Console()

    try:
        with Live(console=console, refresh_per_second=30, transient=False) as live:
            # Phase 1: coalesce animation
            for frame in frames:
                live.update(_build_frame(_render_cell_region(frame, gh, gw), version, model, recorder_model))
                time.sleep(0.05 / speed)

            # Phase 2: shine sweeps across the fully-formed text
            for si in range(SHINE_STEPS + 1):
                t = si / SHINE_STEPS
                shine_pos = SHINE_START + t * (SHINE_END - SHINE_START)
                live.update(
                    _build_frame(_render_cell_region(final_frame, gh, gw, shine_pos), version, model, recorder_model)
                )
                time.sleep(SHINE_DELAY / speed)

    except KeyboardInterrupt:
        pass


if __name__ == "__main__":
    show_startup(version="0.1.0", model="gemini-2.5-flash", recorder_model="gemini-2.5-flash-lite", speed=1.0)
